### ISSUE TITLE
Support WebGL in headless browser

### ISSUE THREAD

**Issue by terribleherbst** [trion-development/docker-ng-cli-karma#1]
Would be great if the headless browser would also support WebGL testing. So if the image would include osmesa (i.e. libosmesa) or some parameter for the headless browser instance people could test code which requires WebGL to run.

**Comment by everflux** [comment]
This should be possible indeed, even with chromium.
But the software renderer makes the browser quite slow, therefore I hesitate to use it by default.
I consider providing a separate image that provides WebGL using the software renderer for e2e tests. Is that your primary use case or do you want it for single components as well?

**Comment by terribleherbst** [comment]
Actually I have one single component in my setup which requires WebGL (a map component). Cause this component is required on multiple pages, I would need it more in e2e testing (which are disabled right now) and in a single component test.

**Comment by everflux** [comment]
I added a WebGL software renderer based on Mesa. Since all rendering is performed using that software layer, the browser will be much slower. I added it as a separate launcher called "xvfb-chromium-webgl" in the latest image. Can you test if this solves your issue?

**Comment by terribleherbst** [comment]
I will check this as soon as possible. Unfortunatly there is little time at the moment, so give me a few days.

**Comment by sroettering** [comment]
I can't seem to get this running.
Can you provide a simple example project with WebGL enabled?

**Comment by everflux** [comment]
The wrapper script was missing the executable bit in the pushed repo, preventing it from running.
Can you try again, if it works for you now? I look into providing a sample project as well.

**Comment by sroettering** [comment]
It is working now, thank you! I had to include the karma-script-launcher plugin, however, or else the browser could not be started.

**Comment by everflux** [comment]
Test project is here: https://github.com/codecoster/ng-wegbl-demo Veryfied to work in e2e scenario with the container.
