### ISSUE TITLE
[Help wanted] Access Docker logs inside Jenkins

### ISSUE THREAD

**Issue by C0ZEN** [trion-development/docker-ng-cli-karma#11]
Following the issue #10.

I would like to see the logs of Docker.
To access - or enable - the logs of Docker inside Jenkins, is there a specific configuration related to this Docker image or is it something common to any Docker image inside Jenkins?

## Reminder

I use the Docker image like this:

`docker.image("trion/ng-cli-karma").inside("--entrypoint='' -e HOME=${userHome}") { ... }`

Thank you.

**Comment by everflux** [comment]
Do you want to see the logs of the Docker daemon or output of the container ?

**Comment by C0ZEN** [comment]
@everflux You are always so fast to respond 👍🏻 

Since the related issue is still a thing I want to access all the logs I can find to help me to identify the culprit. 👿 
I want to see logs related to files - whole size of a build, all metrics I can have on CPU/Ram/Fs -.

So If you know how to configure Jenkins to output both Docker and container logs it would be wonderful.
It's really like a needle in a haystack here... 😢

**Comment by everflux** [comment]
There is no special configuration required to get logging from this image.
The error from the other issue is a general communication problem between your docker client and the docker daemon.
You can diagnose this using a shell on the jenkins machine and manually executing the steps from the jenkins build (jenkinsfile). To increase the logging use `--log-level debug` when executing commands.
In addition to that you can print the complete environment (as well as in the build) and check for DOCKER_* variables - if that points to the wrong daemon host this is your culprit.

**Comment by C0ZEN** [comment]
This error happen:

`docker ps`
`docker: error while loading shared libraries: cannot make segment writable for relocation: Cannot allocate memory`

I have no clue if this is something related to this image or if it could happen for anyone.

**Comment by everflux** [comment]
This is a broken system. Perhaps a raspberry or something very limited or the Setup is broken. 
You can check with 
free -m

Perhaps a reboot helps. This is not related to this image but your environment.
