### ISSUE TITLE
Rebuild with Node 14.5.3

### ISSUE THREAD

**Issue by ErrorProne** [trion-development/docker-ng-cli-karma#12]
Hi everyone,

thanks for the awesome work. Could you maybe trigger a re-build of this and the ng-cli-image?
There is a bug in node 14.5.2, which should be fixed in 14.5.3, causing karma pipeplines to fail.
The current image runs on node 14.5.2 or at least that is what the cli output tells me.

For reference see:
https://github.com/karma-runner/karma/issues/3588
https://github.com/karma-runner/karma/issues/3571

**Comment by everflux** [comment]
Thanks for bringing this to our attention, I will look into it.

**Comment by ErrorProne** [comment]
We've just switched our pipeline to use the freshly build latest-image and it works like a charm :+1: 
Thank you very much

**Comment by everflux** [comment]
That was quick - I just wanted to write about the updated latest build ;)
Glad it works out for you, don't hesitate to open a new issue if anything comes up. Thank you for your contribution!
