### ISSUE TITLE
No docker tag for 14.2.8

### ISSUE THREAD

**Issue by olistrik** [trion-development/docker-ng-cli-karma#17]
Hi there, our CI automatically looks for `trion/ng-cli` and `trion/ng-cli-karma` images to match the version of `ng-cli` we have specified in our package.json. Currently it can't find one for `trion/ng-cli-karma`, I'm guessing because the build images action for the 14.2.8 tag failed.

Would it be possible to publish the 14.2.8 tag to docker hub?

**Comment by everflux** [comment]
Thanks, it should be fixed now.
