### ISSUE TITLE
--single-run true  Unknown argument: single-run

### ISSUE THREAD

**Issue by PigeonT** [trion-development/docker-ng-cli-karma#18]
the ng test will not be automatically run and exit, 
docker run -u $(id -u) --rm -v "$PWD":/app trion/ng-cli-karma ng test --watch false --single-run true
ERROR:
Error: Unknown argument: single-run

**Comment by everflux** [comment]
The `--single-run` switch was removed, the replacement is `--watch false`.
I will update the documentation, thanks.

**Comment by wagenrace** [comment]
Hey, at the moment the documentation on docker-hub still has "single-run"
https://hub.docker.com/r/trion/ng-cli-karma
