### ISSUE TITLE
Add label org.opencontainers.image.source

### ISSUE THREAD

**Issue by marwin1991** [trion-development/docker-ng-cli-karma#19]
Hello, for tools like renovate it is important to have define label org.opencontainers.image.source

So can we add label org.opencontainers.image.source="https://github.com/angular/angular-cli" to DOCKERFILE or add here some CHANGELOG.md and point to this repo?

Base on this label, renovate will provide information about changes.

https://docs.renovatebot.com/modules/datasource/docker/
https://github.com/opencontainers/image-spec/blob/main/annotations.md

The base idea behind this label is to point to repo with dockerfile, but this repo does not use tag's or releases.

What do you think?

**Comment by everflux** [comment]
Sounds good, could you do a PR?

**Comment by marwin1991** [comment]
cc @everflux

**Comment by everflux** [comment]
Thank you!
