### ISSUE TITLE
How to add known_hosts?

### ISSUE THREAD

**Issue by Epenance** [trion-development/docker-ng-cli-karma#2]
Hi there,

I'm using your image to test and release my application, however I'm currently getting "Host key verification failed." when trying to SSH to my server.

Usually I would simply echo the information into the known_hosts file however it seems to be ignored when im trying to do exactly that with the command: "ssh-keyscan -t rsa myserver.com >> ~/.ssh/known_hosts"

If I use more on the file it can see that it doesn't indeed get pasted into the known hosts file, but when connecting it just seems to have been ignored.

Any ideas as to what could be causing this?

**Comment by everflux** [comment]
I am not quite sure what you are trying to achieve and what you are doing...

- The idea of the container is to have a clean environment mit each execution, so when you do a docker-run with --rm everything inside the container gets deleted after the command finishes.
- So if you are modyfing the known-hosts file *inside* the container, perhaps as part of your build, it will have no effect on the outside. That is the very idea of using a container for isolation :)
- I suggest that you use the container just for building/testing the app. Deployment is something different and should happen outside of this container.

Last, but not least, you can disable the host key verification in case your remote side switches often and you use a deployment ssh key which does not need to be kept that secure as regular keys....

`ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" user@myserver.com`
