### ISSUE TITLE
17.1.0 upgrade changed the userId 

### ISSUE THREAD

**Issue by KissBalazs** [trion-development/docker-ng-cli-karma#23]
We use this image to run the unit tests for our angular project. After updating to the new version, our jobs started to fail after running the unit tests (successfully) while trying to write the coverage reports: 

```
9 01 2024 08:15:55.644:ERROR [coverage]: Unexpected error while generating coverage report.
 [Error: EACCES: permission denied, mkdir '/builds/ivu/<projectname>/frontend/ngapp/coverage'] {
```

The difference is 

```
root@oraclegitlab:~# docker run -it --rm trion/ng-cli-karma id
uid=1000(node) gid=1000(node) groups=1000(node)
root@oraclegitlab:~# docker run -it --rm trion/ng-cli-karma:17.0.10 id
uid=0(root) gid=0(root) groups=0(root)
```

A different user runs the commands now (instead of root, now they are run by node).

**Comment by alfrefi** [comment]
I believed it happened the same to me

```
#14 85.06 npm ERR! code EACCES
#14 85.06 npm ERR! syscall open
#14 85.06 npm ERR! path /app/package.json
#14 85.06 npm ERR! errno -13
#14 85.06 npm ERR! Error: EACCES: permission denied, open '/app/package.json'
#14 85.06 npm ERR!  [Error: EACCES: permission denied, open '/app/package.json'] {
#14 85.06 npm ERR!   errno: -13,
#14 85.06 npm ERR!   code: 'EACCES',
#14 85.06 npm ERR!   syscall: 'open',
#14 85.06 npm ERR!   path: '/app/package.json'
#14 85.06 npm ERR! }
#14 85.06 npm ERR!
#14 85.06 npm ERR! The operation was rejected by your operating system.
#14 85.06 npm ERR! It is likely you do not have the permissions to access this file as the current user
#14 85.06 npm ERR!
#14 85.06 npm ERR! If you believe this might be a permissions issue, please double-check the
#14 85.06 npm ERR! permissions of the file and its containing directories, or try running
#14 85.06 npm ERR! the command again as root/Administrator.
``` 

I had to change **trion/ng-cli-karma:latest** to **trion/ng-cli-karma:17.0.10**

**Comment by everflux** [comment]
This is indeed a bug, thanks for reporting.

**Comment by everflux** [comment]
Should be fixed when build is finished.

**Comment by jcconnell** [comment]
Noticed it was commented out here, but not in the E2E image. Should they be the same?

https://github.com/trion-development/docker-ng-cli-e2e/blob/d977170531175947bf4c1689e1598f8670a21de6/Dockerfile#L19

**Comment by everflux** [comment]
That was in place since 2017 so I don't intend to change it, as that would possibly break current usage. (In fact it was a mistake that this was not put in place in the base image, but changing it to the 'correct' behavior lead to this bug report.
