### ISSUE TITLE
yarn not working on latest version

### ISSUE THREAD

**Issue by bufke** [trion-development/docker-ng-cli-karma#4]
Using this image for CI. Started today to get 

$ yarn install
/bin/bash: line 71: /usr/local/bin/yarn: Permission denied

**Comment by everflux** [comment]
Thanks for pointing out the issue. This seems to be the same as https://github.com/nodejs/docker-node/issues/661
I will look into a workaround.

**Comment by everflux** [comment]
Could you please check if the current (latest or 1.7.3) images work for you?

**Comment by bufke** [comment]
Seems to be working now - thanks!
