### ISSUE TITLE
How to tell which version of chrome is installed in image?

### ISSUE THREAD

**Issue by SubjectiveReality** [trion-development/docker-ng-cli-karma#9]
Is there an easy way to tell which version is installed per version tag of the image when built?  If not, might it be possible to specify in the commit message when adding a new image version? Or something.  

Love this, by the way!

**Comment by everflux** [comment]
Thank you for your feedback!

Docker tags are quite inflexible, I will add a LABEL for `chrome` (for `node` and the angular cli version labels are already present). Does that fit your use case?

**Comment by SubjectiveReality** [comment]
Yes, that's great, thank you! Incidentally, I realized after posting that I could do a docker run to get it that way as well.

```
docker pull trion/ng-cli-e2e:8.3.20
docker run $(docker images trion/ng-cli-e2e:8.3.20 -q) /bin/sh -c "google-chrome --version"
```

**Comment by everflux** [comment]
The labels will allow to inspect/filter the version without actually starting a container, might help in specific cases. Once again, thanks for taking the time to provide your feedback!

**Comment by SubjectiveReality** [comment]
Yes labels are much better, thanks again to you for making that update!
